// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt4M-r6I3r9FHS2BooVz_APDx8nfgp73Y',
    appId: '1:688148676972:web:63023ba5f66bdec7877349',
    messagingSenderId: '688148676972',
    projectId: 'campusx-39502',
    authDomain: 'campusx-39502.firebaseapp.com',
    storageBucket: 'campusx-39502.firebasestorage.app',
    measurementId: 'G-43D3VC4LXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_IcGyWimN_5HSadqSi0Y2sJeBzcI86k',
    appId: '1:688148676972:android:c63a966d5e4027a7877349',
    messagingSenderId: '688148676972',
    projectId: 'campusx-39502',
    storageBucket: 'campusx-39502.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCojU0qhKETGALUHu9W0JGDh4E_aDEpbDk',
    appId: '1:688148676972:ios:6f8295663ff65b6f877349',
    messagingSenderId: '688148676972',
    projectId: 'campusx-39502',
    storageBucket: 'campusx-39502.firebasestorage.app',
    iosBundleId: 'com.example.campusx',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCojU0qhKETGALUHu9W0JGDh4E_aDEpbDk',
    appId: '1:688148676972:ios:6f8295663ff65b6f877349',
    messagingSenderId: '688148676972',
    projectId: 'campusx-39502',
    storageBucket: 'campusx-39502.firebasestorage.app',
    iosBundleId: 'com.example.campusx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt4M-r6I3r9FHS2BooVz_APDx8nfgp73Y',
    appId: '1:688148676972:web:495360e92da4e45e877349',
    messagingSenderId: '688148676972',
    projectId: 'campusx-39502',
    authDomain: 'campusx-39502.firebaseapp.com',
    storageBucket: 'campusx-39502.firebasestorage.app',
    measurementId: 'G-VH6YLT9TDE',
  );
}
